---
version: "2"
run:
  allow-parallel-runners: true
  allow-serial-runners: true
linters:
  default: none
  enable:
    - asasalint
    - copyloopvar
    - cyclop
    - durationcheck
    - errorlint
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosmopolitan
    - govet
    - ineffassign
    - ireturn
    - maintidx
    - makezero
    - nestif
    - nolintlint
    - staticcheck
  settings:
    cyclop:
      max-complexity: 30
      package-average: 0
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
    maintidx:
      under: 30
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/EelisK/artbit
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
