---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      # Format
      - id: ruff
        args: [--fix]
      # Imports
      - id: ruff
        args: [check, --select, I, --fix]
      # Lint
      - id: ruff-format
