#!/bin/bash

if ! command -v arp-scan &>/dev/null; then
    echo "arp-scan could not be found"
    exit
fi

if ! command -v jq &>/dev/null; then
    echo "jq could not be found"
    exit
fi

IPV4_REGEX="\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"

RASPI_MAC_OUIS=(
    "b8:27:eb"
    "dc:a6:32"
    "e4:5f:01"
    "dc:44:b6"
    "d8:a0:1d"
    "f4:5c:89"
    "2c:cf:67"
)

sudo arp-scan \
    --localnet \
    --interface="$(
        ip route | grep default | awk '{print $5}' | head -n1
    )" |
    tail -n +2 |
    grep -E "$IPV4_REGEX" |
    while read -r line; do
        mac_addr=$(echo "$line" | awk '{print $2}')
        ip_addr=$(echo "$line" | awk '{print $1}')
        for mac_oui in "${RASPI_MAC_OUIS[@]}"; do
            if echo "$mac_addr" | grep -q "$mac_oui"; then
                echo "$ip_addr"
            fi
        done
    done | sort -u | jq -R -s '
{
  "raspberrypi": {
    "hosts": (split("\n") | map(select(length > 0))),
    "vars": {
      "ansible_connection": "ssh",
      "ansible_user": "pi",
      "ansible_password": "raspberry"
    }
  }
}'
