---
- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install pipx
  ansible.builtin.pip:
    name: pipx
    state: present
    break_system_packages: true

- name: Install poetry
  community.general.pipx:
    name: poetry
    state: present
