#!/bin/bash

# shellcheck disable=SC2016

if [ -z "$1" ]; then
  echo "Usage: $0 <host>"
  exit 1
fi

if ! command -v sshpass &>/dev/null; then
  echo "sshpass is not installed"
  exit 1
fi

HOST=$1

sshpass -p "raspberry" \
  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
  pi@"${HOST}" \
  -t 'cd /opt/artbit; . $(/home/pi/.local/bin/poetry env info --path)/bin/activate; python -m artbit' |
  grep 'VOLTAGE' |
  cut -d' ' -f2-
