---
# yamllint disable rule:line-length

name: "Setup Poetry"
description: "This action checks out the commit and sets up Poetry."

inputs:
  python-version:
    description: "The version of Python to use."
    required: false
    default: "3.9"
  poetry-version:
    description: "The version of Poetry to use."
    required: false
    default: "1.8.2"
  token:
    description: "Personal access token (PAT) used to fetch the repository."
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: "${{ inputs.poetry-version }}"
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Set up cache
      uses: actions/cache@v4
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ poetry.python-version }}-${{ inputs.poetry-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install
