---
- name: update | Make sure the artbit core directory exists
  ansible.builtin.file:
    path: "{{ artbit_core_path }}"
    state: directory
    mode: "0755"

- name: update | Clone repository
  ansible.builtin.git:
    repo: "{{ artbit_core_repo_url }}"
    dest: "{{ artbit_core_path }}"
    version: "{{ artbit_core_repo_branch }}"
    update: yes

- name: update | Install update script
  ansible.builtin.template:
    dest: "/bin/artbit_update"
    src: "artbit_update.j2"
    mode: "0755"

- name: update | Install artbit_pull service
  ansible.builtin.template:
    dest: "/etc/systemd/system/artbit_pull.service"
    src: "artbit_pull.service.j2"
    mode: "0644"

- name: update | Configure cron job to run the update script
  ansible.builtin.cron:
    name: "Check for git updates and restart service"
    user: "{{ ansible_user }}"
    job: "/bin/artbit_update"
    minute: "{{ artbit_core_update_interval }}"
    state: present
    cron_file: "artbit_pull"
