---
# yamllint disable rule:truthy

name: Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get python version
        id: python-version
        run: |
          echo "value=$(cat .python-version)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ steps.python-version.outputs.value }}
      - name: Check formatting with ruff
        run: |
          source .venv/bin/activate
          ruff check
      - name: Check imports with ruff
        run: |
          source .venv/bin/activate
          ruff check --select I
      - name: Check types with pyright
        run: |
          source .venv/bin/activate
          pyright

  ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get python version
        id: python-version
        run: |
          echo "value=$(cat .python-version)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ steps.python-version.outputs.value }}
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          setup_python: "false"
