---
# yamllint disable rule:truthy

name: Producer Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./producer
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24"
      - name: Unit tests
        run: go test -v ./...
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.24"
          workdir: "./producer"
          golangci_lint_flags: "--config=.golangci.yaml"
