---
- name: Copy firmware files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ artbit_firmware_path }}/{{ item }}"
    mode: "0755"
  with_items:
    - config.txt
  notify: "Restart device"
